Add a SettingsSaved event to the ShokoEventHandler
ShokoAnime/ShokoServer pull request #935
Opened 2022-06-29 16:36 UTC by revam

for use in plugins (and in the api when the SignalR emitter/(hub is
added)

2022-06-29 23:30 UTC, Cazzar commented
Personally not the biggest fan of exposing the settings in the Event context, as it does contain user sensitive details

2022-06-30 06:56 UTC, revam commented
So should we just remove the `Before` and `After` properties then?

2022-07-04 00:53 UTC, Cazzar requested changes

2022-07-04 00:53 UTC, Cazzar commented on Shoko.Server/Server/ShokoEventHandler.cs
> +            });
```suggestion
            SettingsSaved?.Invoke(null, new SettingsSavedEventArgs());
```

no point having the extra lines/object constructor if nothing is used, we can always add it in if needed.

2022-07-08 10:23 UTC, merged