Add episode percentage
ShokoAnime/ShokoServer pull request #944
Opened 2022-07-09 23:15 UTC by revam

Because we want to render the percentage some places in Web UI.

Example from @ElementalCrisis's mock-ups;
![image](https://user-images.githubusercontent.com/7761729/178125465-0412771c-0ac3-4640-b5e3-e5e6aaad50e5.png)

2022-07-09 23:22 UTC, revam commented
Will merge late Sunday (local time) unless somebody wants something changed.

2022-07-10 12:01 UTC, Cazzar requested changes

2022-07-10 12:03 UTC, revam commented on Shoko.Server/API/v3/Controllers/DashboardController.cs
> +            var user = HttpContext.GetUser();
It was deliberate.

2022-07-10 12:03 UTC, revam commented on Shoko.Server/API/v3/Controllers/DashboardController.cs
> +            var user = HttpContext.GetUser();
Though yes, it's unrelated and should not have been included in this PR probably.

2022-07-10 12:04 UTC, Cazzar commented on Shoko.Server/API/v3/Controllers/DashboardController.cs
> +            var user = HttpContext.GetUser();
My point still stands though :)

2022-07-10 12:05 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +            public EpisodeDetails(VideoLocal_User userData, SVR_VideoLocal file, AniDB_Episode episode, SVR_AniDB_Anime anime, SVR_AnimeSeries series = null)
I added the the new constructor with the parameters in rising order from the smallest entry to the largest; so the file user data, then the file, then the episode, then the anime, and last the shoko series.

2022-07-10 12:07 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +            public EpisodeDetails(VideoLocal_User userData, SVR_VideoLocal file, AniDB_Episode episode, SVR_AniDB_Anime anime, SVR_AnimeSeries series = null)
It can be changed if you really want to.

2022-07-10 12:07 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +                    ResumePercentage = (int) Math.Round((decimal)(userData.ResumePosition / file.Duration * 100));
We can include the duration and resume position instead and leave it to the front end. Actually, that may be the better idea.

2022-07-10 12:09 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +            public bool SeriesInCollection { get; set; }
Will leave it be then.

Forgot to prefix it when it was added and afaik it's not used yet since it was introduced recently.

2022-07-10 12:10 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Episode.cs
> +                    return Tuple.Create(file, userData);
Will change it.

2022-07-10 12:10 UTC, revam commented on Shoko.Server/API/v3/Controllers/DashboardController.cs
> +                    return Tuple.Create(episode, file, userData);
Will change it.

2022-07-10 14:02 UTC, revam commented
Tried to touch as little as possible in the new files while adding the server model (and removing any references to the non-server model) for the user records.

2022-07-10 14:03 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +                    ResumePercentage = (int) Math.Round((decimal)(userData.ResumePosition / file.Duration * 100));
Changed.

2022-07-10 14:24 UTC, revam commented
I did have one breaking change in the last rebase; the `ResumePosition` for the `File` was changed from a `long` to a `TimeSpan`. But afaik then no current or previous client have used the field to date.

2022-07-11 11:10 UTC, bigretromike commented
are there any v3 endpoints that got broken or old code should work without issue ?

2022-07-11 17:06 UTC, revam commented
@bigretromike see my last comment/message. That's the only breaking change.

2022-07-11 17:07 UTC, revam commented
Is Nakamori still using api v2?

2022-07-12 07:20 UTC, bigretromike commented
> > Is Nakamori still using api v2?
> 
> It's not used in the v3 data models used in Nakamori it seems, so I still don't think the field have ever been used before.

we did v3 some time ago. If those changes break things we will need to rewrite some code, thats why im asking.
Then again, why not make another v3 version like it was done before. like v3.1 its a good thing to not break compatible.

2022-07-12 08:16 UTC, revam commented
And i'm saying i know what I broke (and when it was introduced) and I am not familiar with any current or previous clients using the field within the last ~2 years since it was introduced. Also i will rather revert the type to a `long` than create another api sub version.

2022-07-12 08:58 UTC, ElementalCrisis commented
Even though APIv3 has been in the works for a while, it's still in dev and subject to breaking changes. As Nakamori is currently using it, maybe @revam you can tag @bigretromike anytime APIv3 is updated with a breaking change so he stays informed?

2022-07-12 09:09 UTC, Cazzar commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +            public EpisodeDetails(VideoLocal_User userData, SVR_VideoLocal file, AniDB_Episode episode, SVR_AniDB_Anime anime, SVR_AnimeSeries series = null)
I would add new, optional parameters at the end instead of doing the override constructor.

2022-07-12 11:29 UTC, bigretromike commented
> Even though APIv3 has been in the works for a while, it's still in dev and subject to breaking changes. As Nakamori is currently using it, maybe @revam you can tag @bigretromike anytime APIv3 is updated with a breaking change so he stays informed?

That would be awesome - that or just add changelog with information that function is not backward compatible anymore.

@ElementalCrisis it's been in work as was v2 before, Shoko API won't ever be `finished` its always something that will evolve with rest of the code. You guys introduce sub api versions, and imo thats best place to put anything that otherwise break compatible - but im not forcing that anyway.

2022-07-12 13:40 UTC, da3dsoul commented
Sure things are constantly changing, but we've done a really good job of not breaking apiv2

2022-07-12 16:42 UTC, Cazzar commented
Api sub versions are nice but for a small change like this it is entirely overkill and not worth adding it.
When the discussion was made about the potentially breaking change, we decided to accept that risk as APIv3 is as @ElementalCrisis mentioned, still in its “active development/unfinished” state unlike apiv1/apiv2

2022-07-12 16:53 UTC, revam commented on Shoko.Server/API/v3/Models/Shoko/Dashboard.cs
> +            public EpisodeDetails(VideoLocal_User userData, SVR_VideoLocal file, AniDB_Episode episode, SVR_AniDB_Anime anime, SVR_AnimeSeries series = null)
Removed the secondary constructor and added the parameters in the order of most importance (so the least important ones can be omitted).

2022-07-12 22:26 UTC, da3dsoul commented
I think it's fine

2022-07-13 13:59 UTC, merged